import { initAuth } from './modules/auth';
import { initAsistencias } from './modules/asistencias';
import { initAulas } from './modules/aulas';
import { initBitacora } from './modules/bitacora';
import { initCalificaciones } from './modules/calificaciones';
import { initCatalogosAcademicos } from './modules/catalogos-academicos';
import { initDashboard } from './modules/dashboard';
import { initDistribucionGrupos } from './modules/distribucion-grupos';
import { initDocentesMaterias } from './modules/docentes-materias';
import { initHabilitacion } from './modules/habilitacion';
import { initHorariosGrupos } from './modules/horarios-grupos';
import { initPagos } from './modules/pagos';
import { initPeriodoAcademico } from './modules/periodo-academico';
import { initPortalSidebar } from './modules/portal-sidebar';
import { initPreinscripciones } from './modules/preinscripciones';
import { initRequisitos } from './modules/requisitos';
import { initRolesPermisos } from './modules/roles-permisos';
import { initSession } from './modules/session';
import { initUsuarios } from './modules/usuarios';

document.addEventListener('DOMContentLoaded', () => {
    initAuth();
    initSession();
    initPortalSidebar();
    initDashboard();
    initBitacora();
    initUsuarios();
    initRolesPermisos();
    initPreinscripciones();
    initRequisitos();
    initPagos();
    initHabilitacion();
    initHorariosGrupos();
    initPeriodoAcademico();
    initDistribucionGrupos();
    initDocentesMaterias();
    initAulas();
    initCalificaciones();
    initAsistencias();
    initCatalogosAcademicos();
});
